### ISSUE TITLE
Propably bug in ShouldBeEqual message

### ISSUE THREAD

**Issue by skoczo** [joel-costigliola/assertj-guava#17]
Expected value is showed as actual and actual as expected.

return messageFormatter.format(description, representation, EXPECTED_BUT_WAS_MESSAGE_USING_COMPARATOR,
	                                 <b>detailedActual()</b>,
	                                 <b>detailedExpected()</b>, comparisonStrategy);

private static final String EXPECTED_BUT_WAS_MESSAGE_USING_COMPARATOR = "\nExpecting:\n <b><%s></b>\nto be equal to:\n " +
	"<b><%s></b>\n%s but was not.";

**Comment by joel-costigliola** [comment]
indeed, it has been fixed in assertj-core https://github.com/joel-costigliola/assertj-core/issues/201, next release of assertj-guava will use a version of assertj-core including the fix.

Thanks for taking the time to report it.

**Comment by skoczo** [comment]
Which version should i use to have this fix?
No i'm using:
<dependency>
                          <groupId>org.assertj</groupId>
                          <artifactId>assertj-core</artifactId>
                          <version>1.7.1</version>
</dependency>


2015-02-20 10:52 GMT+01:00 Joel Costigliola <notifications@github.com>:

**Comment by joel-costigliola** [comment]
If the pb is still there using core 1.7.1, can you give a test case ?

**Comment by skoczo** [comment]
I'm doing something like
this: Assertions.assertThat(user.getResponses()).isEqualTo(4);

4 is expected value but i got:

Expecting:
 <0>
to be equal to:
 <4>
but was not.

2015-02-20 11:29 GMT+01:00 Joel Costigliola <notifications@github.com>:

**Comment by skoczo** [comment]
Next question what licence is for your library?

2015-02-20 12:02 GMT+01:00 Adrian Skoczylas <adrian.skoczylas@gmail.com>:

**Comment by joel-costigliola** [comment]
https://github.com/joel-costigliola/assertj-core/blob/master/LICENSE.txt

**Comment by joel-costigliola** [comment]
the error message is fine, you expect 4 but got 0.
