### ISSUE TITLE
assertj-guava does not support assertj-core 3.0.0

### ISSUE THREAD

**Issue by ggtools** [joel-costigliola/assertj-guava#18]

**Comment by joel-costigliola** [comment]
Which version do you used.
I have tested assert-core 3.0 + assertj-guava 1.3.1 and it worked fine

**Comment by ggtools** [comment]
Ok I found the issue it's a little bit tricky. I was trying to use version ranges for both `assertj-core` and `assertj-guava`:

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>[3.0.0,)</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-guava</artifactId>
            <version>[1.3.1,)</version>
            <scope>test</scope>
        </dependency>

Doing this seems to trigger extra checks on version dependencies leading to the following error:

    [ERROR] Failed to execute goal on project adhefi-revamp: Could not resolve dependencies for project com.evollis.cacf.utils:adhefi-revamp:jar:0.1.0-SNAPSHOT: Failed to collect dependencies for com.evollis.cacf.utils:adhefi-revamp:jar:0.1.0-SNAPSHOT: Could not resolve version conflict among [org.assertj:assertj-core:jar:[3.0.0,), org.assertj:assertj-guava:jar:[1.3.0,) -> org.assertj:assertj-core:jar:[1.7.1,1.8.0)] -> [Help 1]

Using a fixed version for `assertj-core` solves the issue

**Comment by joel-costigliola** [comment]
What is weird is that it's showing `org.assertj:assertj-guava:jar:[1.3.0,)` ... I'm closing the issue as there is a fix.
