### ISSUE TITLE
MultimapAssert.isEqualTo(...) should be Multimap implementation intolerant

### ISSUE THREAD

**Issue by pfoermer** [joel-costigliola/assertj-guava#19]
Dear team,

I would expect, that MultimapAssert.isEqualTo(...) is not aware of the concrete Multimap implementation, so that the following test case works. Whats your opinion?

import org.assertj.guava.api.Assertions;
import org.junit.Test;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.ImmutableMultimap;

public class MultimapAssertionTest {

    @Test
    public void testIsEqualBehavesAsExpected() {
        Object key = new Object();
        HashMultimap<Object, Object> hashMultimap = HashMultimap.create();
        hashMultimap.put(key, key);
        ImmutableMultimap<Object, Object> immutableMultimap = ImmutableMultimap.of(key, key);

        /*
         * This fails because of the guava equals implementation which is aware of the map implementation
         * class. A copy compare might be a solution.
         */
        Assertions.assertThat(hashMultimap).isEqualTo(immutableMultimap);
    }

}

**Comment by joel-costigliola** [comment]
`isEqualTo` basically delegates comparison to object under test `equals` method, it would counter intuitive that assertj changed this behaviour.

What we should do instead is to add a new assertions to compare multimaps entries, I suggest something like:

```java
// compare multimap content, without any ordering consideration
assertThat(hashMultimap).hasSameEntriesAs(immutableMultimap);
```
or
```java
// compare multimap content, without any ordering consideration
assertThat(hashMultimap).containsOnlyEntriesOf(immutableMultimap);
// compare multimap content enforcing ordering
assertThat(hashMultimap).containsExactlyEntriesOf(immutableMultimap);
```
I prefer the first option but I would like to hear your opinion.

**Comment by pfoermer** [comment]
Hi Joel,

thank you for your reply. Your suggestions sound good.
I would prefer the word "equal" against the word "same" as long as no object identity comparison is performed.
So
```java
assertThat(hashMultimap).hasEqualEntriesAs(immutableMultimap);
// or
assertThat(hashMultimap).hasEqualMappingAs(immutableMultimap);
```
would be preferrable for me.
However, the problem with the Multimap interface is, that there are two derivations: SetMultimap and ListMultimap. If multiple equal values are mapped to the same key in ListMultimap it can only be equal to a SetMultimap by doing a set based equality check on the values. That would be something like "hasEqualMappingPartitionsAs".
I think the method name "hasEqualEntriesAs(...)" would be the best choice, if the comparison is best on Multimap.entries() and two Mutlimap.entries() can not be "entry equal", if they have different collection sizes.
Possibly we should ask the guava team, if they would provide such an "entry equality" operation in their Multimap API.

Best regards,
Philipp

**Comment by joel-costigliola** [comment]
mmm ... I prefer  `assertThat(hashMultimap).containsOnlyEntriesOf(immutableMultimap)` over `assertThat(hashMultimap).hasEqualEntriesAs(immutableMultimap)` the latter sounds convoluted for me, the use of `contains` should make it clear that we are gonna for a comparison with `equals` method.

I would comparing two entries with the same key by taking their values as Collection and check the collection contents are the same.



Example:
```java
Multimap<String, String> food = ArrayListMultimap.create();
food.put("Fruits", "Apple");
food.put("Fruits", "Bannana");
food.put("Fruits", "Pear");
food.put("Vegetables", "Carrot");


Multimap<String, String> healthyFood = TreeMultimap.create();
// insertion order is different for "Fruits" key
healthyFood.put("Fruits", "Bannana");
healthyFood.put("Fruits", "Apple");
healthyFood.put("Fruits", "Pear");
healthyFood.put("Vegetables", "Carrot");

// should succeeds
assertThat(food).containsOnlyEntriesOf(healthyFood)

```

**Comment by pfoermer** [comment]
Ok.
In my opinion ```java assertThat(hashMultimap).containsOnlyEntriesOf(immutableMultimap) ``` defines, that hashMultimap is a "sub map" of immutableMap, but not vice versa. I would not expect an equal relation for "containsOnly".
But at last it is up to you :).
The insertion order for keys or values might differ between the different Multimap implementation but I guess you meant that.

**Comment by joel-costigliola** [comment]
What you describe would be the behavior of  `assertThat(hashMultimap).containsEntriesOf(immutableMultimap)`.
 
I'm using `containsOnlyEntriesOf` to be consistent with assertj-core where  `assertThat(list).containsOnlyElementsOf(list2)` will check that `list` contains elements of `list2` and nothing else (but order does not matter).

**Comment by joel-costigliola** [comment]
BTW, contributions are welcome ;-)

**Comment by joel-costigliola** [comment]
To implement:
* `containsEntriesOf`
* `containsOnlyEntriesOf`

**Comment by joel-costigliola** [comment]
fixed
