### ISSUE TITLE
COMPILATION ERROR: cannot find symbol: class StrictAssertions location: package org.assertj.core.api

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-guava#23]
I can not build current master:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project assertj-guava: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Redhawk/dev/assertj-guava/src/main/java/org/assertj/guava/api/OptionalAssert.java:[16,35] cannot find symbol
[ERROR] symbol:   class StrictAssertions
[ERROR] location: package org.assertj.core.api
[ERROR] /C:/Users/Redhawk/dev/assertj-guava/src/main/java/org/assertj/guava/api/OptionalAssert.java:[16,1] static import only from classes and interfaces

**Comment by joel-costigliola** [comment]
done
