### ISSUE TITLE
assertj-guava not usable in osgi

### ISSUE THREAD

**Issue by amergey** [joel-costigliola/assertj-guava#28]
Hello,

currently assertj-guava uses classes from core internal package (org.assertj.core.internal.Failures and
org.assertj.core.internal.Objects) so in osgi metdata it imports org.assertj.core.internal package, but this package is not exported in assertj-core, that makes this bundle not usable in osgi.

Error like this:
Missing requirement: org.assertj.guava 2.0.0 requires 'package org.assertj.core.internal 0.0.0' but it could not be found

If Failures and Objects are meant to be used by other components, they  should probably be moved in a "public" package, that would be exported by core, so assertj-guava would import it instead of internal package

**Comment by joel-costigliola** [comment]
Is solved once assertj-guava will depend on assertj-core 2.3.0 as per this commit https://github.com/joel-costigliola/assertj-core/commit/b45abcbdfe4cffb99f4f0812d8f7a09b056c5e35

**Comment by nickstolwijk** [comment]
When do you think 2.3.0 will be released?

**Comment by joel-costigliola** [comment]
I'm planning to release it next week !

**Comment by nickstolwijk** [comment]
Nice!
