### ISSUE TITLE
Support for Java 8 and AssertJ 3.x?

### ISSUE THREAD

**Issue by bcalmac** [joel-costigliola/assertj-guava#29]
From the pom.xml dependency for assertj-core [2.1.0, 2.99.0] I infer that assertj-guava is not compatible with AssertJ 3.x and Java 8. Are there current plans to get it working?

I tried to see if it works anyway (assertj-guava 2.0.0 + assertj-core 3.2.0) and the following test:

```java
	@Test
	public void assertjMultimapTest() {
		assertThat(ImmutableListMultimap.of(6, "Mickey", 6, "Minnie", 3, "Goofy"))
			.hasSameEntriesAs(ImmutableListMultimap.of(6, "Mickey", 6, "Minnie", 5, "Goofy"));
	}
```

fails with the exception below. It looks related to type inference changes from Java 8.

```
java.lang.NoSuchMethodError: org.assertj.core.error.ShouldContainOnly.shouldContainOnly(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Iterable;)Lorg/assertj/core/error/ErrorMessageFactory;

	at org.assertj.guava.api.MultimapAssert.hasSameEntriesAs(MultimapAssert.java:286)
	at com.panduit.util.stream.PCollectorsTest.assertjMultimapTest(PCollectorsTest.java:15)
```

**Comment by joel-costigliola** [comment]
@bcalmac I will release by the end of the year a new assertj-guava version (probably 3.0.0) compatible with assertj-core 3.x. version.

**Comment by bcalmac** [comment]
Good timing :-) If there's any way I can help, let me know.

**Comment by joel-costigliola** [comment]
Well, I was expecting someone to (rightfully) complain ;-)

**Comment by joel-costigliola** [comment]
AssertJ Guava 3.0.0 released.
Can you give it a try ?

**Comment by bcalmac** [comment]
My test case works now, thanks.

**Comment by joel-costigliola** [comment]
Thanks for the feedback :+1:
