### ISSUE TITLE
assertj-guava 2.0 tries to use guava 21

### ISSUE THREAD

**Issue by Rubbiroid** [joel-costigliola/assertj-guava#38]
Hallo,

in my project I#m bound to java 7, so I can't use asserj-guava v3+ and guava.v20+.
Gradle build takes guava 21 (latest) as a transitive dependency, which is wrong. Can you please adapt the pom file to use maximal guava 19?
I can force the version in gradle, but it is not a good solution.

Kind regards,
Pavel

**Comment by joel-costigliola** [comment]
Will do !

**Comment by joel-costigliola** [comment]
likely solved by https://github.com/joel-costigliola/assertj-guava/pull/37

**Comment by joel-costigliola** [comment]
Note that guava 20 is java 7 compatible so we will use it instead of 19.

**Comment by joel-costigliola** [comment]
Fixed but can't release 2.0.1 due to sonatype error publishing to maven central https://issues.sonatype.org/browse/OSSRH-39602.

**Comment by joel-costigliola** [comment]
released: http://search.maven.org/#artifactdetails%7Corg.assertj%7Cassertj-guava%7C2.0.1%7Cbundle!
