### ISSUE TITLE
Optional .contains() does not work with primitive arrays

### ISSUE THREAD

**Issue by chrisly42** [joel-costigliola/assertj-guava#42]
When I added a transformation from

assertThat(optional.get()).isEqualTo(foobar);
to
assertThat(optional).contains(foobar);

this did not produce equivalent results for primitive arrays. Turns out that the contains() assertion uses .equals() directly instead of a comparing using a comparing strategy like isEqualTo() does.

**Comment by joel-costigliola** [comment]
Good catch @chrisly42,  thanks for the PR too!
